layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: UiPath
    web_url: https://github.com/topics/uipath
    image_url: https://www.uipath.com/hubfs/Valentin/Brand-Kit/logos/UiPath-full-logo.svg?v=2.0

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png

  - name: Spring Boot
    web_url: https://github.com/topics/springboot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png

  - name: Payara
    web_url: https://github.com/topics/payara
    image_url: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJMYXllcl8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIKCSB2aWV3Qm94PSIwIDAgNjQyIDIzMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ieE1pbllNaW4gbWVldCIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+Cgkuc3Qwe2ZpbGw6I0YwOTgxQjt9Cgkuc3Qxe2ZpbGw6I0ZGRkZGRjt9Cjwvc3R5bGU+CjxnPgoJPGc+CgkJPGc+CgkJCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0xNS41LDE4Ny4xYzUuNCwxMi4zLDE4LjgsMjgsMjEsMjkuN2MtMy4xLDUuNi04LjQsNi44LTguNCw2LjhTMTQuOCwyMDEuOSwxNS41LDE4Ny4xeiIvPgoJCTwvZz4KCQk8cGF0aCBjbGFzcz0ic3QwIiBkPSJNNy43LDE5MC40YzQuMywxMi43LDE3LjIsMzAuMSwxOS4yLDMyLjFjLTMuNiw1LjMtOS45LDUuNC05LjksNS40UzUuOCwyMDUsNy43LDE5MC40eiIvPgoJCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0yOTYuNSwxYzAsMC03OS42LDIwLjEtOTMuNSw0NGMtMzMuMy01LjktODkuOCwzLTg5LjgsM3MtNS42LTM2LjctMS40LTQ3QzIyLjUsNDQsNC4xLDEzNi40LDEsMTg2LjRsMCwwCgkJCWMwLDAsMjUuNS0xMi4yLDUwLjEsMmMxLTAuNy0xNi42LDMxLjgtMzQuMiwzOS40Yy0wLjIsMC4xLDEuMSwwLjMsMC45LDAuNGMxOC0wLjcsNTYuOC0xNyw3NC43LTMxLjIKCQkJYzU5LjItNDcuMSw1MS4xLTc5LjksNTEuMS03OS45cy0yNy4zLDQzLjYtNDguOSwxNi4xYy0xNy0yMS42LDM0LTcwLjksMTE5LjMtNTUuOWM1MC44LDguOSw4Mi41LDMxLDgyLjUsMzFMMjQ5LDU2TDI5Ni41LDF6CgkJCSBNNTAuMSwxNjQuOWMtMy42LDQuNC04LjMsNS0xMi4yLDIuOGMtNS4zLTMsNC4xLTI0LjUsMTcuNS0yNS41QzU1LjQsMTQyLjEsNTUuMiwxNTguNyw1MC4xLDE2NC45eiBNODYuMSwxMTIuNAoJCQljMCwwLDMuOS0yMy4zLTIxLTQxLjZDOTIuNiw4MC4zLDk1LjIsOTUuNCw4Ni4xLDExMi40eiBNOTQuMiwxMDIuNWMwLDAsMy4zLTE5LjUtMTcuNS0zNC44Qzk5LjYsNzUuNiwxMDEuOCw4OC4zLDk0LjIsMTAyLjV6CgkJCSBNMTAxLjIsOTIuNmMwLDAsMi42LTE1LjctMTQuMS0yOEMxMDUuNiw3MSwxMDcuMyw4MS4yLDEwMS4yLDkyLjZ6IE0xMDcuMiw4My40YzAsMCwyLTExLjktMTAuNy0yMS4yCgkJCUMxMTAuNSw2NywxMTEuOSw3NC44LDEwNy4yLDgzLjR6Ii8+Cgk8L2c+Cgk8cGF0aCBjbGFzcz0ic3QxIiBkPSJNMTU2LjgsMjI5di02NS41YzAtNi40LDAuMy0xMS40LDEtMTVjMC42LTMuNiwxLjctNi44LDMuMi05LjhjMy4xLTYuNCw3LjctMTEuNSwxMy44LTE1LjEKCQljNi0zLjYsMTIuOC01LjQsMjAuMi01LjRjMTEsMCwyMC4xLDMuNywyNy4zLDExLjFjNy4yLDcuNCwxMC43LDE2LjcsMTAuNywyOC4xYzAsNS4xLTAuOSwxMC4xLTIuNywxNC44Yy0xLjgsNC43LTQuMyw4LjktNy43LDEyLjUKCQljLTMuNCwzLjgtNy41LDYuOC0xMi4yLDguOGMtNC43LDIuMS05LjcsMy4xLTE0LjgsMy4xYy0zLjgsMC03LjQtMC40LTEwLjgtMS4zYy0zLjQtMC44LTYuNy0yLjEtOS44LTMuOXYtMTQuNgoJCWMzLjEsMi40LDYuMiw0LjEsOS40LDUuM2MzLjIsMS4xLDYuNCwxLjcsOS43LDEuN2M3LjMsMCwxMy4yLTIuNSwxNy45LTcuNWM0LjctNSw3LTExLjQsNy0xOS4yYzAtNy42LTIuMy0xMy45LTYuOS0xOC44CgkJYy00LjYtNC45LTEwLjUtNy4zLTE3LjYtNy4zYy03LjIsMC0xMywyLjUtMTcuNSw3LjRzLTYuNywxMS4zLTYuNywxOS4zVjIyOUgxNTYuOHoiLz4KCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0zMDEuOSwxOTUuM3YtMzcuOGMwLTcuOS0yLjItMTQuNC02LjctMTkuM2MtNC41LTQuOS0xMC4zLTcuNC0xNy41LTcuNGMtNy4xLDAtMTIuOSwyLjQtMTcuNSw3LjMKCQljLTQuNiw0LjktNi44LDExLjEtNi44LDE4LjhjMCw3LjgsMi4zLDE0LjIsNywxOS4yYzQuNyw1LDEwLjcsNy41LDE3LjksNy41YzMuMywwLDYuNS0wLjYsOS42LTEuN3M2LjItMi45LDkuNC01LjN2MTQuNgoJCWMtMy4xLDEuOC02LjMsMy4xLTkuOCwzLjljLTMuNCwwLjgtNywxLjMtMTAuOCwxLjNjLTMuNiwwLTcuMi0wLjYtMTAuNy0xLjdzLTYuOC0yLjctOS43LTQuN2MtNS41LTMuOC05LjYtOC41LTEyLjUtMTQuMQoJCXMtNC4zLTExLjktNC4zLTE4LjhjMC0xMS4zLDMuNi0yMC43LDEwLjctMjguMWM3LjItNy40LDE2LjItMTEuMSwyNy4zLTExLjFjNy4zLDAsMTMuOSwxLjgsMTkuOSw1LjVzMTAuNyw4LjcsMTMuOSwxNS4xCgkJYzEuNSwyLjksMi42LDYsMy4yLDkuNWMwLjYsMy40LDEsOC41LDEsMTUuM3YzMS44aC0xMy42VjE5NS4zeiIvPgoJPHBhdGggY2xhc3M9InN0MSIgZD0iTTM4Ny4yLDExOS42djQxLjNjMCw5LjctMi4xLDE3LjQtNi4zLDIzLjNjLTQuMiw1LjgtMTAuNiw5LjgtMTkuMiwxMS45VjIyOWgtMTMuNnYtMzIuOQoJCWMtOC41LTIuMS0xNC45LTYuMS0xOS4xLTExLjlzLTYuMy0xMy42LTYuMy0yMy4zdi00MS4zaDEzLjV2NDMuOGMwLDYsMS44LDEwLjgsNS4zLDE0LjZzOCw1LjYsMTMuNSw1LjZzMTAtMS45LDEzLjUtNS42CgkJYzMuNS0zLjgsNS4yLTguNiw1LjItMTQuNnYtNDMuOEwzODcuMiwxMTkuNkwzODcuMiwxMTkuNnoiLz4KCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik00NTYuOSwxOTUuM3YtMzcuOGMwLTcuOS0yLjItMTQuNC02LjctMTkuM2MtNC41LTQuOS0xMC4zLTcuNC0xNy41LTcuNGMtNy4xLDAtMTIuOSwyLjQtMTcuNSw3LjMKCQljLTQuNiw0LjktNi44LDExLjEtNi44LDE4LjhjMCw3LjgsMi4zLDE0LjIsNywxOS4yYzQuNyw1LDEwLjcsNy41LDE3LjksNy41YzMuMywwLDYuNS0wLjYsOS42LTEuN2MzLjEtMS4xLDYuMi0yLjksOS40LTUuM3YxNC42CgkJYy0zLjEsMS44LTYuMywzLjEtOS44LDMuOWMtMy40LDAuOC03LDEuMy0xMC44LDEuM2MtMy42LDAtNy4yLTAuNi0xMC43LTEuN3MtNi44LTIuNy05LjctNC43Yy01LjUtMy44LTkuNi04LjUtMTIuNS0xNC4xCgkJcy00LjMtMTEuOS00LjMtMTguOGMwLTExLjMsMy42LTIwLjcsMTAuNy0yOC4xYzcuMi03LjQsMTYuMi0xMS4xLDI3LjMtMTEuMWM3LjMsMCwxMy45LDEuOCwxOS45LDUuNXMxMC43LDguNywxMy45LDE1LjEKCQljMS41LDIuOSwyLjYsNiwzLjIsOS41YzAuNiwzLjQsMSw4LjUsMSwxNS4zdjMxLjhoLTEzLjZWMTk1LjN6Ii8+Cgk8cGF0aCBjbGFzcz0ic3QxIiBkPSJNNDc5LjksMTk1LjN2LTc1LjhoMTIuNXYxMS4yYzIuMy00LjQsNS41LTcuNiw5LjYtOS42czkuNS0zLDE2LjUtM2gzLjZ2MTMuMUg1MjBjLTkuMywwLTE2LjEsMi4yLTIwLjIsNi42CgkJYy00LjEsNC40LTYuMiwxMS42LTYuMiwyMS42djM1LjhoLTEzLjdWMTk1LjN6Ii8+Cgk8cGF0aCBjbGFzcz0ic3QxIiBkPSJNNTg0LjIsMTk1LjN2LTM3LjhjMC03LjktMi4yLTE0LjQtNi43LTE5LjNjLTQuNS00LjktMTAuMy03LjQtMTcuNS03LjRjLTcuMSwwLTEyLjksMi40LTE3LjUsNy4zCgkJYy00LjYsNC45LTYuOCwxMS4xLTYuOCwxOC44YzAsNy44LDIuMywxNC4yLDcsMTkuMmM0LjcsNSwxMC43LDcuNSwxNy45LDcuNWMzLjMsMCw2LjUtMC42LDkuNi0xLjdzNi4yLTIuOSw5LjQtNS4zdjE0LjYKCQljLTMuMSwxLjgtNi4zLDMuMS05LjgsMy45Yy0zLjQsMC44LTcsMS4zLTEwLjgsMS4zYy0zLjYsMC03LjItMC42LTEwLjctMS43cy02LjgtMi43LTkuNy00LjdjLTUuNS0zLjgtOS42LTguNS0xMi41LTE0LjEKCQlzLTQuMy0xMS45LTQuMy0xOC44YzAtMTEuMywzLjYtMjAuNywxMC43LTI4LjFjNy4yLTcuNCwxNi4yLTExLjEsMjcuMy0xMS4xYzcuMywwLDEzLjksMS44LDE5LjksNS41czEwLjcsOC43LDEzLjksMTUuMQoJCWMxLjUsMi45LDIuNiw2LDMuMiw5LjVjMC42LDMuNCwxLDguNSwxLDE1LjN2MzEuOGgtMTMuNlYxOTUuM3oiLz4KCTxnPgoJCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik02MDEuNiwxMDFjMC0wLjQsMC4xLTAuOCwwLjItMS4zYzAuMS0wLjQsMC4yLTAuOCwwLjMtMS4zYzAuMS0wLjQsMC4zLTAuOSwwLjQtMS4zYzAuNS0xLjYsMS4zLTMuMSwyLjMtNC42CgkJCXMyLjMtMi45LDMuOS00LjJjMS41LTEuMywzLjMtMi40LDUuMy0zYzItMC43LDQuMi0xLDYuNi0xYzIuNywwLDUuMSwwLjUsNy4zLDEuNGMyLjIsMSw0LjIsMi40LDUuOSw0LjNjMS44LDEuOSwzLjEsMy45LDQsNS45CgkJCWMwLjksMi4xLDEuNCw0LjIsMS40LDYuNXYwLjF2MC4xYy0wLjEsMy0wLjYsNS42LTEuNiw3LjljLTEsMi4zLTIuNCw0LjMtNC4yLDUuOWMtMS44LDEuNi0zLjgsMi44LTUuOSwzLjYKCQkJYy0yLjEsMC44LTQuMiwxLjItNi41LDEuMmgtMC4xaC0wLjFoLTAuMWgtMC4xaC0wLjFjLTAuMSwwLTAuMSwwLTAuMSwwaC0wLjFoLTAuMWMtMy4xLTAuMS01LjctMC42LTgtMS42CgkJCWMtMi4zLTAuOS00LjItMi4zLTUuNy00LjJjLTEuNS0xLjgtMi43LTMuNy0zLjUtNS43cy0xLjMtNC4xLTEuNC02LjNjMC0wLjEsMC0wLjEsMC0wLjJjMCwwLDAtMC4xLDAtMC4ydi0wLjFjMC0wLjEsMC0wLjEsMC0wLjEKCQkJYzAtMC4xLDAtMC4yLDAtMC4zczAtMC4yLDAtMC4zdi0wLjFDNjAxLjUsMTAxLjgsNjAxLjYsMTAxLjQsNjAxLjYsMTAxeiBNNjA2LjgsMTA4LjRjMC42LDEuOCwxLjYsMy40LDIuOCw0LjkKCQkJYzEuMywxLjQsMi44LDIuNSw0LjYsMy4zYzEuOCwwLjcsMy45LDEuMSw2LjMsMS4xYzAuNCwwLDAuNywwLDEuMS0wLjFjMC40LDAsMC44LTAuMSwxLjItMC4yYzAuNC0wLjEsMC44LTAuMiwxLjItMC4zCgkJCXMwLjgtMC4yLDEuMi0wLjRjMS4yLTAuNCwyLjMtMSwzLjMtMS43YzEuMS0wLjgsMi4xLTEuNywzLTIuOGMxLTEuMSwxLjctMi41LDIuMy00LjFjMC41LTEuNiwwLjgtMy41LDAuOS01LjYKCQkJYzAtMS45LTAuMy0zLjctMS01LjRzLTEuNy0zLjMtMy00LjhzLTIuOS0yLjYtNC42LTMuNGMtMS43LTAuOC0zLjYtMS4xLTUuNy0xLjFoLTAuMWMtMC4xLDAtMC4xLDAtMC4xLDBjLTAuMSwwLTAuMSwwLTAuMiwwCgkJCWMwLDAtMC4xLDAtMC4yLDBoLTAuMWMtMC4xLDAtMC4xLDAtMC4xLDBjLTAuMSwwLTAuMSwwLjEtMC4yLDAuMWMwLDAtMC4xLDAtMC4yLDBjLTEuNywwLjEtMy4zLDAuNS00LjksMS4yCgkJCWMtMS42LDAuNy0zLDEuNi00LjUsMi45Yy0xLjQsMS4yLTIuNSwyLjctMy4yLDQuNWMtMC43LDEuNy0xLjEsMy44LTEuMSw2di0wLjFDNjA1LjksMTA0LjcsNjA2LjIsMTA2LjcsNjA2LjgsMTA4LjR6IE02MTMsOTIuMgoJCQloOC43YzEuNywwLjIsMywwLjQsNC4xLDAuOGMxLDAuNCwxLjcsMC45LDIsMS41YzAuNCwwLjYsMC42LDEuMywwLjgsMnMwLjMsMS40LDAuMywyLjJzLTAuMSwxLjUtMC4zLDIuMmMtMC4yLDAuNi0wLjUsMS4yLTEsMS43CgkJCWMtMC40LDAuNS0xLDAuOC0xLjcsMS4xcy0xLjUsMC41LTIuNSwwLjZsNS45LDloLTRsLTUuNS05LjFoLTMuMnY5LjFINjEzVjkyLjJ6IE02MjIuOSwxMDEuMmMwLjYtMC4xLDEtMC40LDEuNC0wLjcKCQkJYzAuMy0wLjMsMC42LTAuNiwwLjgtMXMwLjMtMC44LDAuMy0xLjN2LTAuMVY5OGMwLTAuNC0wLjEtMC43LTAuMy0xLjFjLTAuMi0wLjMtMC40LTAuNy0wLjgtMWMtMC4zLTAuMy0wLjgtMC41LTEuNC0wLjcKCQkJYy0wLjYtMC4yLTEuMy0wLjMtMi4yLTAuM2wtNC0wLjF2Ni4zaDQuM0M2MjEuNywxMDEuNCw2MjIuNCwxMDEuNCw2MjIuOSwxMDEuMnoiLz4KCTwvZz4KPC9nPgo8L3N2Zz4K

  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/csharp/csharp.png
  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png

  - name: Angular
    web_url: https://github.com/topics/angular
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png

  - name: jQuery
    web_url: https://github.com/topics/jquery
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/jquery/jquery.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: MySql
    web_url: https://github.com/topics/mysql
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mysql/mysql.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
